# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\VScode\funny-QRcode\advancedWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_advancedWindow(object):
    def setupUi(self, advancedWindow):
        advancedWindow.setObjectName("advancedWindow")
        advancedWindow.resize(339, 336)
        self.verticalLayout = QtWidgets.QVBoxLayout(advancedWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.versionLabel = QtWidgets.QLabel(advancedWindow)
        self.versionLabel.setObjectName("versionLabel")
        self.horizontalLayout.addWidget(self.versionLabel)
        self.versionEdit = QtWidgets.QLineEdit(advancedWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versionEdit.sizePolicy().hasHeightForWidth())
        self.versionEdit.setSizePolicy(sizePolicy)
        self.versionEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.versionEdit.setObjectName("versionEdit")
        self.horizontalLayout.addWidget(self.versionEdit)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leverLabel = QtWidgets.QLabel(advancedWindow)
        self.leverLabel.setObjectName("leverLabel")
        self.horizontalLayout_2.addWidget(self.leverLabel)
        self.leverBox = QtWidgets.QComboBox(advancedWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leverBox.sizePolicy().hasHeightForWidth())
        self.leverBox.setSizePolicy(sizePolicy)
        self.leverBox.setObjectName("leverBox")
        self.leverBox.addItem("")
        self.leverBox.addItem("")
        self.leverBox.addItem("")
        self.leverBox.addItem("")
        self.horizontalLayout_2.addWidget(self.leverBox)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(11)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.colorizedLabel = QtWidgets.QLabel(advancedWindow)
        self.colorizedLabel.setObjectName("colorizedLabel")
        self.horizontalLayout_5.addWidget(self.colorizedLabel)
        self.colorizedBox = QtWidgets.QComboBox(advancedWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorizedBox.sizePolicy().hasHeightForWidth())
        self.colorizedBox.setSizePolicy(sizePolicy)
        self.colorizedBox.setObjectName("colorizedBox")
        self.colorizedBox.addItem("")
        self.colorizedBox.addItem("")
        self.horizontalLayout_5.addWidget(self.colorizedBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.contrastLabel = QtWidgets.QLabel(advancedWindow)
        self.contrastLabel.setObjectName("contrastLabel")
        self.horizontalLayout_6.addWidget(self.contrastLabel)
        self.constractEdit = QtWidgets.QLineEdit(advancedWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.constractEdit.sizePolicy().hasHeightForWidth())
        self.constractEdit.setSizePolicy(sizePolicy)
        self.constractEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.constractEdit.setObjectName("constractEdit")
        self.horizontalLayout_6.addWidget(self.constractEdit)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.brightLabel = QtWidgets.QLabel(advancedWindow)
        self.brightLabel.setObjectName("brightLabel")
        self.horizontalLayout_7.addWidget(self.brightLabel)
        self.brightEdit = QtWidgets.QLineEdit(advancedWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brightEdit.sizePolicy().hasHeightForWidth())
        self.brightEdit.setSizePolicy(sizePolicy)
        self.brightEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.brightEdit.setObjectName("brightEdit")
        self.horizontalLayout_7.addWidget(self.brightEdit)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton = QtWidgets.QPushButton(advancedWindow)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_8.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_8)

        self.retranslateUi(advancedWindow)
        QtCore.QMetaObject.connectSlotsByName(advancedWindow)

    def retranslateUi(self, advancedWindow):
        _translate = QtCore.QCoreApplication.translate
        advancedWindow.setWindowTitle(_translate("advancedWindow", "高级选项"))
        self.versionLabel.setText(_translate("advancedWindow", "边长（1-40）"))
        self.versionEdit.setText(_translate("advancedWindow", "5"))
        self.leverLabel.setText(_translate("advancedWindow", "纠错等级"))
        self.leverBox.setItemText(0, _translate("advancedWindow", "H"))
        self.leverBox.setItemText(1, _translate("advancedWindow", "L"))
        self.leverBox.setItemText(2, _translate("advancedWindow", "M"))
        self.leverBox.setItemText(3, _translate("advancedWindow", "Q"))
        self.colorizedLabel.setText(_translate("advancedWindow", "上色（是/否）"))
        self.colorizedBox.setItemText(0, _translate("advancedWindow", "否"))
        self.colorizedBox.setItemText(1, _translate("advancedWindow", "是"))
        self.contrastLabel.setText(_translate("advancedWindow", "对比度"))
        self.constractEdit.setText(_translate("advancedWindow", "1.0"))
        self.brightLabel.setText(_translate("advancedWindow", "亮度"))
        self.brightEdit.setText(_translate("advancedWindow", "1.0"))
        self.pushButton.setText(_translate("advancedWindow", "确定"))

